[package]
name = "pinger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console-subscriber = "0.1.8"
futures = "0.3.28"
surge-ping = "0.8.0"
tokio = { version = "1.28.0", features = ["full"] }
